#-Information---------------------------------------------------------------------------------------
name: whats_my_species
version: 1.0
target: sample
type: pipeline
recommendation: required
description: >
  This runs kraken/bracken on a sample in order to determine the species found in the sample. Reads
  are first filtered using bbduk. The species is then set for the sample from this.
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
adapters_fasta: "../../resources/adapters.fasta"
kraken_database: "/path_to_db/kraken/minikraken_20171019_8GB/"
kraken_kmer_dist: "/path_to_db/kraken/minikraken_20171019_8GB/minikraken_8GB_100mers_distrib.txt"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  # None
#---------------------------------------------------------------------------------------------------