#-Information---------------------------------------------------------------------------------------
name: qcquickie
version: 1.0
target: sample
type: pipeline
recommendation: recommended
description: >
  This does de-novo assembly on a sample and then maps the reads back against the denovo assembly
  for variant calling. In the process it gathers metrics on many aspects for the use of QC. This
  generates the same metrics as assemblatron but prioritizes speed. It is also used to help 
  correlate metrics for comparing other assemblers. It is not recommended to use these contigs for 
  downstream analysis
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
adapters_fasta: "../../resources/adapters.fasta"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  # None
#---------------------------------------------------------------------------------------------------
